name: mohesu_model
description: A new Flutter package project.
version: 0.0.2
homepage: https://github.com/mohesu

environment:
  sdk: ">=2.19.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dartx: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  flutter_lints: ^2.0.1

flutter:
